export const productdata = [
  {
    pname: "Mercedes AMG GT",
    pmake: "mercedes-benz",
    pbody: "coupe",
    pcolor: "black",
    pyear: "2022",
    pdesc: "Brand new Mercedes AMG GT 63",
    model: "AMG-GT",
    transmission: "AutoMatic",
    pcondition: "brand new",
    pPrice: 125000000,
    // img: GT63S,
    pImage: "./amg-gt-63-s.jpg",
    slug: "amg-gt-63",
  },
  {
    pname: "Mercedes AMG GT 53 Coupe",
    pmake: "mercedes-benz",
    pbody: "coupe",
    pcolor: "white",
    pyear: "2022",
    pdesc: "Brand new Mercedes AMG GT 53 White Coupe",
    // model: "AMG-GT",
    transmission: "AutoMatic",
    pcondition: "brand new",
    pPrice: 95000000,
    pImage: "./gt-63.jpg",
    slug: "amg-gt-53",
  },
  {
    pname: "Mercedes AMG GT",
    pmake: "mercedes-benz",
    pbody: "coupe",
    pcolor: "black",
    pyear: "2022",
    pdesc: "Brand new Mercedes AMG GT 63",
    model: "AMG-GT",
    transmission: "AutoMatic",
    ppcondition: "used",
    pPrice: 125000000,
    pImage: "./amg-gt-63-s.jpg",
    slug: "amg-gt-63",
  },
  {
    pname: "Mercedes AMG GT",
    pmake: "mercedes-benz",
    pbody: "coupe",
    pcolor: "black",
    pyear: "2022",
    pdesc: "Brand new Mercedes AMG GT 63",
    model: "AMG-GT",
    transmission: "AutoMatic",
    pcondition: "brand new",
    pPrice: 125000000,
    pImage: "./amg-gt-63-s.jpg",
    slug: "amg-gt-63",
  },
  {
    pname: "Mercedes AMG GT",
    pmake: "mercedes-benz",
    pbody: "coupe",
    pcolor: "black",
    pyear: "2022",
    pdesc: "Brand new Mercedes AMG GT 63",
    model: "AMG-GT",
    transmission: "AutoMatic",
    pcondition: "used",
    pPrice: 125000000,
    pImage: "./amg-gt-63-s.jpg",
    slug: "amg-gt-63",
  },
  {
    pname: "Lamborghini Huracan STO",
    pmake: "lamborghini",
    pbody: "coupe",
    pcolor: "blue",
    pyear: "2023",
    pdesc: "2023 Brand new Lamborghini Huracan STO",
    model: "STO",
    transmission: "AutoMatic",
    pcondition: "brand new",
    pPrice: 350000000,
    pImage: "./huracan sto.jpg",
    slug: "lamborghini-sto",
  },
  {
    pname: "Lamborghini STO",
    pmake: "lamborghini",
    pbody: "coupe",
    pcolor: "blue",
    pyear: "2023",
    pdesc: "2023 Used Lamborghini Huracan STO",
    model: "STO",
    transmission: "AutoMatic",
    pcondition: "used",
    pPrice: 350000000,
    pImage: "./sto_04_m.jpg",
    slug: "lamborghini-sto",
  },
];
